In [1]:
import pandas as pd
df = pd.read_csv("customer_shopping_behavior.csv")

In [2]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
df['Customer ID'].nunique()

3900

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [5]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [6]:
df.isna().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [7]:
print(df[df["Review Rating"].isnull()])

      Customer ID  Age Gender Item Purchased     Category  \
38             39   29   Male          Dress     Clothing
50             51   49   Male         Blouse     Clothing
80             81   19   Male        Sandals     Footwear
96             97   32   Male         Gloves  Accessories
262           263   37   Male          Pants     Clothing
330           331   46   Male        Sweater     Clothing
356           357   56   Male          Pants     Clothing
383           384   50   Male     Sunglasses  Accessories
419           420   53   Male         Shorts     Clothing
442           443   29   Male     Sunglasses  Accessories
452           453   45   Male          Pants     Clothing
460           461   64   Male          Shoes     Footwear
491           492   49   Male           Coat    Outerwear
512           513   19   Male         Gloves  Accessories
560           561   25   Male        Jewelry  Accessories
628           629   69   Male        Sweater     Clothing
799           800   55   Male           Belt  Accessories
829           830   42   Male          Socks     Clothing
861           862   46   Male          Skirt     Clothing
888           889   49   Male          Scarf  Accessories
1072         1073   48   Male         Shorts     Clothing
1109         1110   66   Male         Hoodie     Clothing
1124         1125   42   Male        Sweater     Clothing
1134         1135   62   Male        T-shirt     Clothing
1151         1152   41   Male         Blouse     Clothing
1176         1177   36   Male          Dress     Clothing
1189         1190   64   Male          Shirt     Clothing
1208         1209   20   Male          Boots     Footwear
1220         1221   67   Male         Gloves  Accessories
1230         1231   25   Male            Hat  Accessories
1247         1248   65   Male        T-shirt     Clothing
1292         1293   26   Male           Belt  Accessories
1313         1314   70   Male          Shoes     Footwear
1326         1327   40   Male          Shoes     Footwear
1334         1335   46   Male           Coat    Outerwear
1341         1342   26   Male         Hoodie     Clothing
1370         1371   27   Male          Scarf  Accessories

      Purchase Amount (USD)        Location Size     Color  Season  \
38                       37         Florida    M       Red  Winter
50                       28        Maryland    M       Red  Spring
80                       72        New York   XL      Blue  Summer
96                       73        Delaware    S      Gold  Spring
262                      40          Hawaii    M      Teal  Summer
330                      51    North Dakota    M     Beige  Winter
356                      80          Nevada    L     Black  Spring
383                      77   West Virginia    S   Magenta    Fall
419                      91            Utah    S      Teal  Winter
442                      69        Michigan    M     Olive    Fall
452                      45        Missouri    M    Violet  Summer
460                      65  South Carolina    L      Teal  Summer
491                      69         Vermont    M    Silver  Summer
512                      49        New York    L     Peach  Winter
560                      48       Louisiana    L       Red    Fall
628                      85   Massachusetts    M     White    Fall
799                      55          Nevada    L     Brown  Summer
829                      57           Idaho    S    Silver  Spring
861                     100        Virginia   XL     Green  Spring
888                      77   New Hampshire    S      Gold  Spring
1072                     92           Idaho    L      Gold    Fall
1109                     97        Oklahoma    L    Violet  Winter
1124                     20            Iowa    M    Orange  Spring
1134                     81       Wisconsin    M     Brown  Summer
1151                     86            Ohio    M      Gray  Spring
1176                     83          Oregon    M       Red  Winter
1189                     97        Arkansas   XL      Teal  Summer
1208                    100       Wisconsin    S       Red  Winter
1220                     64        Kentucky    M     Green  Winter
1230                     80        Illinois    L     Brown  Spring
1247                     99        Virginia    M  Charcoal  Spring
1292                     61        Kentucky    M    Maroon  Summer
1313                     28        Missouri    M  Lavender  Summer
1326                     50           Texas    M    Indigo  Spring
1334                     52   West Virginia    S     White  Spring
1341                     27    Rhode Island   XL    Yellow    Fall
1370                     67         Montana    L     Peach  Summer

      Review Rating Subscription Status   Shipping Type Discount Applied  \
38              NaN                 Yes  2-Day Shipping              Yes
50              NaN                 Yes    Store Pickup              Yes
80              NaN                 Yes    Store Pickup              Yes
96              NaN                 Yes         Express              Yes
262             NaN                 Yes    Next Day Air              Yes
330             NaN                 Yes         Express              Yes
356             NaN                 Yes        Standard              Yes
383             NaN                 Yes        Standard              Yes
419             NaN                 Yes   Free Shipping              Yes
442             NaN                 Yes    Store Pickup              Yes
452             NaN                 Yes         Express              Yes
460             NaN                 Yes    Store Pickup              Yes
491             NaN                 Yes  2-Day Shipping              Yes
512             NaN                 Yes    Next Day Air              Yes
560             NaN                 Yes   Free Shipping              Yes
628             NaN                 Yes  2-Day Shipping              Yes
799             NaN                 Yes   Free Shipping              Yes
829             NaN                 Yes  2-Day Shipping              Yes
861             NaN                 Yes  2-Day Shipping              Yes
888             NaN                 Yes         Express              Yes
1072            NaN                  No         Express              Yes
1109            NaN                  No    Next Day Air              Yes
1124            NaN                  No         Express              Yes
1134            NaN                  No         Express              Yes
1151            NaN                  No         Express              Yes
1176            NaN                  No   Free Shipping              Yes
1189            NaN                  No   Free Shipping              Yes
1208            NaN                  No  2-Day Shipping              Yes
1220            NaN                  No         Express              Yes
1230            NaN                  No        Standard              Yes
1247            NaN                  No         Express              Yes
1292            NaN                  No   Free Shipping              Yes
1313            NaN                  No   Free Shipping              Yes
1326            NaN                  No   Free Shipping              Yes
1334            NaN                  No    Store Pickup              Yes
1341            NaN                  No        Standard              Yes
1370            NaN                  No  2-Day Shipping              Yes

     Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
38               Yes                  44          Venmo         Every 3 Months
50               Yes                  39     Debit Card              Bi-Weekly
80               Yes                  24    Credit Card         Every 3 Months
96               Yes                  43          Venmo         Every 3 Months
262              Yes                   6     Debit Card               Annually
330              Yes                  43          Venmo              Bi-Weekly
356              Yes                  27           Cash                 Weekly
383              Yes                   6         PayPal              Quarterly
419              Yes                  14    Credit Card         Every 3 Months
442              Yes                  31    Credit Card              Quarterly
452              Yes                  39         PayPal            Fortnightly
460              Yes                  27  Bank Transfer                 Weekly
491              Yes                  24    Credit Card              Bi-Weekly
512              Yes                   2  Bank Transfer                Monthly
560              Yes                  12     Debit Card               Annually
628              Yes                  29    Credit Card                Monthly
799              Yes                  31         PayPal               Annually
829              Yes                  14    Credit Card            Fortnightly
861              Yes                  35    Credit Card         Every 3 Months
888              Yes                  44           Cash               Annually
1072             Yes                  34     Debit Card            Fortnightly
1109             Yes                   2          Venmo                 Weekly
1124             Yes                  40           Cash              Quarterly
1134             Yes                   2          Venmo         Every 3 Months
1151             Yes                  24    Credit Card                 Weekly
1176             Yes                  39         PayPal              Quarterly
1189             Yes                  28     Debit Card               Annually
1208             Yes                   8     Debit Card               Annually
1220             Yes                  36  Bank Transfer              Quarterly
1230             Yes                  49          Venmo                Monthly
1247             Yes                  18          Venmo              Bi-Weekly
1292             Yes                  42  Bank Transfer               Annually
1313             Yes                  23    Credit Card              Bi-Weekly
1326             Yes                  17           Cash                Monthly
1334             Yes                  12          Venmo                Monthly
1341             Yes                  31  Bank Transfer              Quarterly
1370             Yes                  41  Bank Transfer         Every 3 Months

In [8]:
df["Review Rating"]=df.groupby("Category")["Review Rating"].transform(lambda x: x.fillna(x.median()))

In [9]:
df.isna().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [10]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [11]:
# Creating a column age group
labels=['Young','Adult','Middle-aged','Senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [12]:
df[['age','age_group']]

      age    age_group
0      55  Middle-aged
1      19        Young
2      50  Middle-aged
3      21        Young
4      45  Middle-aged
...   ...          ...
3895   40        Adult
3896   52  Middle-aged
3897   46  Middle-aged
3898   44        Adult
3899   52  Middle-aged

[3900 rows x 2 columns]

In [13]:
#purchase_frequency_days
freuqency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(freuqency_mapping)

In [14]:
df[['purchase_frequency_days','frequency_of_purchases']]

      purchase_frequency_days frequency_of_purchases
0                          14            Fortnightly
1                          14            Fortnightly
2                           7                 Weekly
3                           7                 Weekly
4                         365               Annually
...                       ...                    ...
3895                        7                 Weekly
3896                       14              Bi-Weekly
3897                       90              Quarterly
3898                        7                 Weekly
3899                       90              Quarterly

[3900 rows x 2 columns]

In [15]:
df[['discount_applied','promo_code_used']]

     discount_applied promo_code_used
0                 Yes             Yes
1                 Yes             Yes
2                 Yes             Yes
3                 Yes             Yes
4                 Yes             Yes
...               ...             ...
3895               No              No
3896               No              No
3897               No              No
3898               No              No
3899               No              No

[3900 rows x 2 columns]

In [16]:
(df['discount_applied']==df['promo_code_used']).all()

True

In [17]:
df = df.drop('promo_code_used',axis=1)

In [19]:
!pip install pymysql sqlalchemy

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 1.2 MB/s eta 0:00:011
Requirement already satisfied: sqlalchemy in ./opt/anaconda3/lib/python3.9/site-packages (1.4.32)
Requirement already satisfied: greenlet!=0.4.17 in ./opt/anaconda3/lib/python3.9/site-packages (from sqlalchemy) (1.1.1)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

In [20]:
import pandas as pd
from sqlalchemy import create_engine

In [21]:
username = "root"
password = "88884444"
host = "localhost"
port = "3306"
database = "customer_behavior_db"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

In [22]:
engine.connect()

In [25]:
table_name = "customer"
df. to_sql(table_name, engine, if_exists="replace", index=False)
pd. read_sql("SELECT * FROM customer LIMIT 5;", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365